# Build
FROM node:20-alpine AS builder

WORKDIR /app

RUN corepack enable

COPY .yarnrc.yml ./
COPY .yarn ./.yarn
COPY package*.json yarn.lock ./

RUN yarn install --immutable

COPY . .

RUN yarn build

# Serve com Nginx
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 1000
CMD ["nginx", "-g", "daemon off;"]