FROM golang:1.25.5-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@v1.63.4

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o worker

CMD ["./worker", "air", "-c", ".air.toml"]